//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipProje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Competent { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Sector { get; set; }
        public string Province { get; set; }
        public string Distirct { get; set; }
        public string Address { get; set; }
    }
}
