//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipProje.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsTakipEntities : DbContext
    {
        public IsTakipEntities()
            : base("name=IsTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLogin> AdminLogin { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<MissionDetails> MissionDetails { get; set; }
        public virtual DbSet<Personels> Personels { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
    }
}
