//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipProje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.MissionDetails = new HashSet<MissionDetails>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Employer { get; set; }
        public Nullable<int> Worker { get; set; }
        public string Descriptions { get; set; }
        public Nullable<bool> Situation { get; set; }
        public Nullable<System.DateTime> DateT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MissionDetails> MissionDetails { get; set; }
        public virtual Personels Personels { get; set; }
        public virtual Personels Personels1 { get; set; }
    }
}
